# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='contact',
        ),
        migrations.AddField(
            model_name='property',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=18),
            preserve_default=False,
        ),
    ]
