# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0002_auto_20170615_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='tags',
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], max_length=3, null=True, verbose_name='Features'),
        ),
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='room_type',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Input your address'),
        ),
        migrations.AddField(
            model_name='comment',
            name='prop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='habitat.Property'),
        ),
    ]
