# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0004_auto_20170704_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
