# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0006_auto_20170704_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=50, verbose_name='* Input your address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='* Email'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Your property name:'),
        ),
        migrations.AlterField(
            model_name='property',
            name='phone',
            field=models.CharField(max_length=18, verbose_name='* Phone'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(verbose_name='* Price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('old_house', 'Old house'), ('high_rise', 'High-rise'), ('villa', 'Villa'), ('service_apt', 'Service Apartment')], default='0', max_length=50, verbose_name='* Select Property Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='room_type',
            field=models.CharField(choices=[('studio', 'Studio'), ('loft', 'Loft'), ('one_br', '1BR'), ('two_br', '2BR'), ('three_br', '3BR'), ('four_br_plus', '4BR+')], default='0', max_length=50, verbose_name='* Select Room Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.FloatField(verbose_name='* Room Size'),
        ),
    ]
