# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0007_auto_20170704_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Your property name:'),
        ),
    ]
