# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0008_auto_20170704_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='pictures', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='images',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
