# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0009_auto_20170706_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='prop',
        ),
    ]
