# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0011_images_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='user',
        ),
    ]
