# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0012_remove_images_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='prop',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='habitat.Property'),
        ),
    ]
