# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0016_auto_20170707_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='prop',
        ),
        migrations.AddField(
            model_name='images',
            name='prop_id',
            field=models.IntegerField(default=-1),
        ),
    ]
