# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0017_auto_20170707_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], max_length=300, null=True, verbose_name='Features'),
        ),
    ]
