# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import habitat.models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0018_auto_20170707_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=habitat.models.get_image_file_by_id, verbose_name='Image'),
        ),
    ]
