# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0019_auto_20170707_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Your property name:'),
        ),
    ]
