# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0021_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='descrption',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
