# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0022_property_descrption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='descrption',
            new_name='description',
        ),
    ]
